[package]
name = "glaz"
description = "Biblioteka UI oparta na wgpu, skoncentrowana na własnych dekoracjach okien, przezroczystości i efektach backdrop."
keywords = ["gui", "wgpu", "transparency", "window-decorations"]
categories = ["gui"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck = { workspace = true }
cosmic-text = { workspace = true }
log = { workspace = true }
lucide-icons = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

[lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
